### ISSUE TITLE
[BUG] Speed msg when leaving zone

### ISSUE THREAD

**Issue by FR33K1LL** [surftimer/SurfTimer#128]
**Describe the bug**
When leaving a zone, the speed is printed in chat. The value printed is not the value shown on the hud.

**Expected behavior**
Print value shown on hud

**Screenshots**
![wrong wr and pb speed in start msg](https://user-images.githubusercontent.com/63484108/82038248-17466800-9658-11ea-86ce-fefd64feb96f.PNG)

(speed in hud is 260, value shown was 299.)

**Plugin List**
List of all your current sourcemod plugins, if applicable to the issue.

**Timer Version**
dev 285.7

**Additional context**
Could this be because of the introduction of the x vel in the db now? So its also taking into account your x speed possibly? Im not really sure.

**Comment by FR33K1LL** [comment]
Additional Context
sorry i forgot to say this wasnt present in 285, didnt want to edit the post.

**Comment by Kyli3Boi** [comment]
I think this is because the spleen on the hud is xy speed and the speed printed in chat is xyz speed. 

The dev's should add the functionality to allow you to either display xy or xyz speed

**Comment by olokos** [comment]
Is this still happening in 1.0.2?

**Comment by qawery-just-sad** [comment]
yes coz it displays speed in xyz @olokos 
imo it should get speed type from playeroptions and use that

**Comment by Bara** [comment]
We should come to a standard... xy or xyz speed. Which is more accurate?

**Comment by FR33K1LL** [comment]
I would prefer xy, but thats just my opinion.

**Comment by Kyli3Boi** [comment]
I would prefer xy also

**Comment by qawery-just-sad** [comment]
ehhh... I see couple of issues with current implementation of prestrafe msgs:
1. should use https://github.com/surftimer/Surftimer-olokos/blob/856e1a5325a480f9ae0fcde372793fa645f81b85/addons/sourcemod/scripting/SurfTimer.sp#L536 to display prestarfe speed that client uses (coz for some reason someone want's to use xyz or z)
2. should display prestrafe msg on end touch of the zone (start/stage/bonus start) currently does that on linear maps and on staged this happenes 
![image](https://user-images.githubusercontent.com/53490397/90231253-2eddea00-de1b-11ea-8dcd-5bf678f49465.png)

3. should display end speed on start touch of the zone (end zone/stage/bonus end) currently displays prestrafe speed from last stage wich should be displayed earlier (like maybe when i leave stage zone, not when i'm in next stage? is it only me?)
![image](https://user-images.githubusercontent.com/53490397/90231879-191cf480-de1c-11ea-95cd-9f7af9290614.png)
so like that `End: xxx u/s [WR: xxx | PR: xxx]` should be a separate msg 
4. change it from saying WR to SR, to keep it consistent across the plugin

5. maybe we don't need to save all 3 speeds in db, we could just save 2 (for example xy and xyz) and then calculate the 3rd in timer (xyz - xy = z)?

**Comment by qawery-just-sad** [comment]
6. idk if it's done already but should match the style that you are using so like for slow-mo it's comparing the slow-mo SR and PR
(no i don't like styles, but i know when we don't do this now, someone that uses for example slow-mo will be like "ohh it doesn't do that, fix it!")

**Comment by Kyli3Boi** [comment]
I would just like to add that all these double messages (as per Justsad number 2 and 3) is messy and unnecessary. It adds clutter and makes it difficult to read when you in a run and want to glance at it. 

Can we please do something about these double messages because they really are annoying

**Comment by DotDivi** [comment]
Cant we have it just like you are able to disable/enable prestrafe messages in chat for stage wrcps and cps in chat  if you just want to see checkpoints on the center timer? Removes alot of chatspam

**Comment by Kyli3Boi** [comment]
Justsad number 2. 
Imo when leaving a zone all we need to know is our speed and the +-SR speed in 1 message. I don't get why we displaying stage speed and the prestrafe speed as they do the same thing.

Could we also perhaps change the format to be Speed xxx u/s [PB +-xxx] [SR +-xxx]

Justsad number 3. 
Please don't make end another message. 
It makes sense what's its doing as its showing you your stage performance. Remember when you leave the stage zone you will be displayed your prestrafe message so if you change this then (currently) you would have 3 messages displaying your speed when leaving a zone. 

Suggest to change format to:
Start xxx u/s [PB +-xxx] [SR +-xxx] | End xxx u/s [PB +-xxx] [SR +-xxx]

Could we also have CP changed to Total time because CP and stage is very confusing, also swap these around 

Suggest to change format to:
Stage x: xx:xx:xx [PB+-xx:xx:xx] [SR+-xx:xx:xx]
Total time: xx:xx:xx [PB+-xx:xx:xx] [SR+-xx:xx:xx]

So at the end of it all it would it would display as per below:

Surftimer | Start xxx u/s [PB +-xxx] [SR +-xxx] | End xxx u/s [PB +-xxx] [SR +-xxx]
Surftimer | Stage x: xx:xx:xx [PB+-xx:xx:xx] [SR+-xx:xx:xx]
Surftimer | Total time: xx:xx:xx [PB+-xx:xx:xx] [SR+-xx:xx:xx]

**Comment by dPexxIAM** [comment]
LUL at people asking for XY speeds when leaving startzones btw
