### ISSUE TITLE
[BUG] infinite loop and SegV after 10s

### ISSUE THREAD

**Issue by LeBatou** [surftimer/SurfTimer#507]
**Describe the bug**
![image](https://user-images.githubusercontent.com/47107713/186031108-a8260b70-de88-4959-b040-d27cba464748.png)
As you can see on the image it loops on this to crash after, the server doesn't boot, before all of those prints, there isn't any errors
proof : 
![image](https://user-images.githubusercontent.com/47107713/186031744-fa4edc9e-1ee2-4e20-9600-b9149fbd5b19.png)

**Expected behavior**
The server starting

**Plugin List**
None except the timer + all non misc requirements

**Comment by LeBatou** [comment]
UPDATE:

The problem was present because I was using "127.0.0.1" for the host in database.cfg and not "localhost"

**Comment by tslashd** [comment]
Is the server hosted on Windows OS by any chance?

**Comment by olokos** [comment]
> UPDATE:
> 
> The problem was present because I was using "127.0.0.1" for the host in database.cfg and not "localhost"

Can you check your /etc/hosts file and make sure you have an entry for 127.0.0.1 and localhost in one line?

AFAIK 127.0.0.1 connects using TCP/IP while with localhost the connection is done via socket (or the other way around)

Having said that, if you:
- Have a proper entry in hosts
- Set your bind address to 127.0.0.1/0.0.0.0

Then everything should work as expected, regardless if you use `localhost` or `127.0.0.1`

![image](https://user-images.githubusercontent.com/1755581/186398908-1a5ef60d-9c8f-4a91-9f9c-84d92b6dfcb2.png)

You can see that I am able to connect to my DB using both, I censored some info for privacy reasons.

What I find odd about this issue is that the logs you provided mention that tables are okay, but then crashes afterwards, which is specifically weird, because you just got confirmation that DB works, but not entirely.

This makes me think there might be some deeper issue here
