### ISSUE TITLE
[BUG] Timer changes player name to bot name

### ISSUE THREAD

**Issue by aKjeller** [surftimer/SurfTimer#75]
**Describe the bug**
Sometimes the timer changes a players name to the infobots name, have only seen this at map start.

**Expected behavior**
This should never happen.

**Screenshots**
![bugg](https://user-images.githubusercontent.com/44802724/80422487-842ed380-88de-11ea-9794-6c2d210e2338.png)

**Plugin List**
surftimer - 285 

**Additional context**
This seems to happen very random at map start!

**Comment by olokos** [comment]
@aKjeller 
Does it still happen for you with 1.0.1?

I didnt experience it myself even once.

**Comment by Bara** [comment]
Are you able to reproduce this with the latest dev Version? If you get any errors, please update or post the errors again.

Don't forget **after updating** surftimer to run the command `sm_surftimer_upgrade` and after this to [.sql](https://github.com/surftimer/Surftimer-Official/blob/dev/scripts/mysql-files/optimizations/ck_change_column_types.sql)-File.

**Comment by Kyli3Boi** [comment]
I have personally never seen this and its never been reported by any of the players using my servers.

**Comment by olokos** [comment]
I can confirm this happens with the latest dev version

It's pretty rare, but usually it happens during the first map after a server was just started, oddly enough there's no logs when this does happen in the server console.

I think this only happens if infobot is enabled on the server, as first player connecting to the server always gets infobot name - when this bug happens, it's never the other bots.

**Comment by Kyli3Boi** [comment]
Very possible why i have never seen this as i do not use the infobot

**Comment by olokos** [comment]
I had server running, but empty so I was on the server with bots, wrote `quit` in server console and joined ASAP as the server was visible, leading to this:

```
L 11/07/2020 - 00:02:21: [surftimer] Starting to load server settings
L 11/07/2020 - 00:02:22: [SurfTimer] Finished loading server settings in 0.750000s
PutClientInServer: no info_player_start on level
L 11/07/2020 - 00:02:22: [Surftimer] Loading STEAM_1:0:58950181 - olopros settings
RecordSteamInterfaceCreation (PID 14201): SteamGameStats001 /
L 11/07/2020 - 00:02:22: [randomcycle.smx] RandomCycle has chosen surf_mjk for the nextmap.
L 11/07/2020 - 00:02:22: [Surftimer] STEAM_1:0:58950181: Finished db_viewPersonalRecords in 0.109375s
ConVarRef sv_voice_proximity_minvolume doesn't point to an existing ConVar
L 11/07/2020 - 00:02:23: [Surftimer] STEAM_1:0:58950181: Finished db_viewPersonalBonusRecords in 0.359375s
L 11/07/2020 - 00:02:23: [Surftimer] STEAM_1:0:58950181: Finished db_viewPersonalStageRecords in 0.015625s
L 11/07/2020 - 00:02:23: [SurfTimer] STEAM_1:0:58950181: Finished db_viewPlayerPoints in 0.593750s
L 11/07/2020 - 00:02:24: [SurfTimer] STEAM_1:0:58950181: Finished db_GetPlayerRank in 0.281250s
L 11/07/2020 - 00:02:24: [SurfTimer] STEAM_1:0:58950181: Finished db_viewPlayerOptions in 0.031250s
L 11/07/2020 - 00:02:24: [SurfTimer] STEAM_1:0:58950181: Finished db_CheckVIPAdmin in 0.015625s
L 11/07/2020 - 00:02:24: [SurfTimer] STEAM_1:0:58950181: Finished db_viewCustomTitles in 0.031250s
L 11/07/2020 - 00:02:24: [SurfTimer] STEAM_1:0:58950181: Finished db_viewCheckpoints in 0.015625s
L 11/07/2020 - 00:02:24: [SurfTimer] Finished loading STEAM_1:0:58950181 - Pending Vote (in Time: 29:52) settings in 1.453125s
```

It seems that players name is changed only once and not updated after that, when this bug occurs.
![Image](https://image.prntscr.com/image/yVZnw8lvQK6junEIm7wNvg.png)

**Comment by olokos** [comment]
One more thing I've noticed, but forgot to mention about this issue.

This happens when player joins right after server startup, but before bots even join the server.

So the course of action is this:

Server is started
Player joins during plugins execution
Player has it's name set as Pending vote
Bots join the server
Bots change their names to what they're supposed to be
Player nickname still remains Pending vote

My idea about this is that Pending vote is being set without checking if the first user connected is a bot, but instead just slapped on the first user that joined the server.

**Comment by dPexxIAM** [comment]
not able to reproduce
